#!/usr/bin/env python3
"""Write the experiment configs for the redo, 20 through 28, from the tuned base.

Every one of these differs from the others in four switches and a cohort and in nothing else:
the encoding arm, both learning schedules, the masking rates and the time loss weight are what
Phase 2 settled, and the history length is what Phase 3 selected. Writing them by hand invites
exactly one failure -- a config that silently carries a different hyperparameter than its
neighbours, which makes its column in the results table incomparable to the rest and says
nothing in the output. Generating them from one base removes that.

Experiment 29 is not written here. It is a logistic regression on age, sex and the Charlson
comorbidity index rather than a TransEHR2 run; `run_charlson_logistic_regression.py` is its
entry point. Experiment 28 is its control and is written here, restricted to the same episodes
through COHORT_EPISODES.

Usage:
    python generate_redo_configs.py --history_len_steps 261
    python generate_redo_configs.py --base TransEHR2/configs/experiments/tuning/phase3_base.yaml \\
        --history_len_steps 261 --charlson_episodes data/charlson_episodes.txt --dry_run

The history length is required rather than defaulted, because the value Phase 3 selects is the
one thing here that is not already recorded in a config.
"""

import argparse
import os
import sys

import yaml


DEFAULT_BASE = os.path.join('TransEHR2', 'configs', 'experiments', 'tuning',
                            'phase3_base.yaml')
DEFAULT_OUTPUT_DIR = os.path.join('TransEHR2', 'configs', 'experiments')
DEFAULT_CHARLSON_EPISODES = os.path.join('data', 'charlson_episodes.txt')

# Keys the base carries for the sweep's sake that an experiment sets for itself. Dropped rather
# than overwritten, so a base that stops setting one does not leave a stale value behind.
BASE_ONLY = ('HYPERPARAMETERS_TO_TUNE',)

# Pretraining ran for 200 epochs during tuning, which was a budget for ranking configurations
# rather than for training the reported models. The final runs get the longer budget.
DEFAULT_PRETRAIN_EPOCHS = 500

# (number, slug, cohort, use_text, historical nontext, historical text, peri-stay, description)
#
# The switches are the four that decide which records reach the model. `USE_TEXT` builds the
# text features at all; the three region switches clear their region's indicators at collation
# time. A model reading historical text but no historical values is a real arm, not an
# oversight -- it is the column that isolates what the text alone carries.
EXPERIMENTS = (
    (20, 'peristay_textsubset', 'any_text', False, False, False, True,
     'Peri-Stay Records Only, Patients With At Least 1 Pre-Admission Text Record'),
    (21, 'history_text_textsubset', 'any_text', True, True, True, False,
     'Historical Records Only, Text Features, Patients With At Least 1 Pre-Admission Text '
     'Record'),
    (22, 'history_peristay_notext_textsubset', 'any_text', False, True, False, True,
     'Peri-Stay + Historical Records, No Text Features, Patients With At Least 1 '
     'Pre-Admission Text Record'),
    (23, 'history_peristay_text_textsubset', 'any_text', True, True, True, True,
     'Peri-Stay + Historical Records, Text Features, Patients With At Least 1 Pre-Admission '
     'Text Record'),
    (24, 'peristay_textonly_textsubset', 'any_text', True, False, True, True,
     'Peri-Stay + Text Features Only, Patients With At Least 1 Pre-Admission Text Record'),
    (25, 'peristay_historysubset', 'any_history', False, False, False, True,
     'Peri-Stay Records Only, Patients With At Least 1 Historical Record'),
    (26, 'history_text_historysubset', 'any_history', True, True, True, False,
     'Historical Records Only, Text Features, Patients With At Least 1 Historical Record'),
    (27, 'history_peristay_text_historysubset', 'any_history', True, True, True, True,
     'Peri-Stay + Historical Records, Text Features, Patients With At Least 1 Historical '
     'Record'),
    (28, 'peristay_charlsonsubset', None, False, False, False, True,
     'Peri-Stay Records Only, Patients With A Charlson Comorbidity Index'),
)

# Experiment 28 is the Charlson control and is selected by an explicit episode list rather than
# by a cohort predicate, because "has a Charlson index" is a property of an earlier admission
# and not of the extracted arrays.
CHARLSON_EXPERIMENT = 28

HEADER = """# Generated by generate_redo_configs.py from {base}.
# Do not edit by hand -- regenerate instead, so every experiment keeps the same
# hyperparameters and differs only in which records reach the model.
#
# {description}

"""


def load_base(path):
    """The tuned base every experiment inherits.

    Args:
        path: Path to the base config.

    Returns:
        The parsed config, with the sweep-only keys removed.

    Raises:
        SystemExit: If the file is missing or carries no hyperparameters.
    """
    if not os.path.exists(path):
        raise SystemExit(
            f'{path} does not exist. It is Phase 2\'s selected configuration, and without it '
            f'these experiments would inherit nothing.'
        )
    with open(path) as handle:
        base = yaml.safe_load(handle) or {}
    for key in BASE_ONLY:
        base.pop(key, None)
    for required in ('MODEL_DIR', 'POSITION_ENCODING', 'PRETRAIN_LEARNING_RATE'):
        if required not in base:
            raise SystemExit(f'{path} sets no {required}; it is not a tuned base config.')
    return base


def build(base, entry, history_len_steps, pretrain_epochs, charlson_episodes):
    """One experiment's config.

    Args:
        base: The parsed base config.
        entry: One row of `EXPERIMENTS`.
        history_len_steps: Crop length Phase 3 selected, or None for the full region.
        pretrain_epochs: Pretraining budget for the final runs.
        charlson_episodes: Episode list for the Charlson control.

    Returns:
        Tuple of (experiment name, config dict, description).
    """
    number, slug, cohort, use_text, hist_nontext, hist_text, peristay, description = entry
    name = f'experiment{number}_{slug}'
    config = dict(base)
    config.update({
        'EXPERIMENT_NAME': name,
        'COHORT_SUBSET': cohort,
        'HISTORY_LEN_STEPS': history_len_steps,
        'PRETRAIN_TOTAL_EPOCH': pretrain_epochs,
        'USE_TEXT': use_text,
        'USE_HISTORICAL_NONTEXT_RECORDS': hist_nontext,
        'USE_HISTORICAL_TEXT_RECORDS': hist_text,
        'USE_INSTAY_RECORDS': peristay,
    })
    if cohort is None:
        config.pop('COHORT_SUBSET')
    if number == CHARLSON_EXPERIMENT:
        config['COHORT_EPISODES'] = charlson_episodes
    return name, config, description


def write(path, name, config, description, base_path):
    """Write one config, header first."""
    with open(path, 'w') as handle:
        handle.write(HEADER.format(base=base_path, description=description))
        yaml.safe_dump(config, handle, default_flow_style=False, sort_keys=True)
    return path


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--base', default=DEFAULT_BASE,
                        help=f'Tuned config every experiment inherits (default: {DEFAULT_BASE})')
    parser.add_argument('--output_dir', default=DEFAULT_OUTPUT_DIR,
                        help=f'Where to write the configs (default: {DEFAULT_OUTPUT_DIR})')
    parser.add_argument('--history_len_steps', type=int, required=True,
                        help='Crop length Phase 3 selected. Pass 0 for no pre-admission '
                             'history; there is no default, because this is the one value not '
                             'already recorded in a config.')
    parser.add_argument('--pretrain_epochs', type=int, default=DEFAULT_PRETRAIN_EPOCHS,
                        help=f'Pretraining budget (default: {DEFAULT_PRETRAIN_EPOCHS}). Tuning '
                             f'ran 200, which was a budget for ranking rather than for the '
                             f'reported models.')
    parser.add_argument('--charlson_episodes', default=DEFAULT_CHARLSON_EPISODES,
                        help=f'Episode list restricting experiment {CHARLSON_EXPERIMENT} to '
                             f'the Charlson cohort (default: {DEFAULT_CHARLSON_EPISODES})')
    parser.add_argument('--only', type=int, nargs='+', default=None,
                        help='Write only these experiment numbers')
    parser.add_argument('--dry_run', action='store_true',
                        help='Print what would be written without writing it')
    args = parser.parse_args(argv)

    base = load_base(args.base)
    entries = [e for e in EXPERIMENTS if args.only is None or e[0] in args.only]
    if not entries:
        raise SystemExit(f'--only {args.only} matches no experiment; they are '
                         f'{[e[0] for e in EXPERIMENTS]}.')

    if not args.dry_run:
        os.makedirs(args.output_dir, exist_ok=True)

    print(f'Base:            {args.base}')
    print(f'History length:  {args.history_len_steps}')
    print(f'Pretrain epochs: {args.pretrain_epochs}')
    print(f'Encoding:        {base["POSITION_ENCODING"]}')
    print(f'Models:          {base["MODEL_DIR"]}\n')

    written = []
    for entry in entries:
        name, config, description = build(base, entry, args.history_len_steps,
                                          args.pretrain_epochs, args.charlson_episodes)
        path = os.path.join(args.output_dir, f'{name}.yaml')
        switches = ''.join('1' if config.get(key) else '0' for key in
                           ('USE_TEXT', 'USE_HISTORICAL_NONTEXT_RECORDS',
                            'USE_HISTORICAL_TEXT_RECORDS', 'USE_INSTAY_RECORDS'))
        cohort = config.get('COHORT_SUBSET') or 'episode list'
        print(f'  {name:<48} {cohort:<14} switches {switches}')
        if not args.dry_run:
            write(path, name, config, description, args.base)
        written.append((entry[0], name, path, description))

    if args.dry_run:
        print('\nDry run: nothing written.')
        return 0

    print(f'\nWrote {len(written)} config(s) to {args.output_dir}/')
    print('\nSwitch columns are USE_TEXT, historical non-text, historical text, peri-stay.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
