"""Expand a finetuning diagnostic: one pretrained encoder, a grid of finetuning schedules.

Finetuning stopped after thirty to forty epochs, which under the patience of thirty in force
at the time put the best model inside the first ten. The grid separates the two candidate causes:
a learning rate high enough to overwrite the pretrained encoder before the head can use it,
and the absence of any annealing. Every cell finetunes from the *same* encoder, so the
comparison is between finetuning schedules and nothing else.

Expand with:
    python generate_finetune_diagnostic.py

Then pretrain once, link the encoder into each cell, and finetune. The script prints the
commands.
"""

import argparse
import os

import yaml

BASE_CONFIG = 'TransEHR2/configs/experiments/tuning/phase2_base.yaml'
OUTPUT_DIR = 'TransEHR2/configs/experiments/ftdiag'
PRETRAIN_NAME = 'ftdiag_pretrain'

# The encoder every cell shares. Additive rather than RoPE because the failure showed up in
# both arms, so the cheaper one is enough to diagnose it, and a half-life of 40 against a
# pretraining run that peaks between epoch 50 and 110 anneals well inside the run.
PRETRAIN_OVERRIDES = {
    'POSITION_ENCODING': 'additive',
    'PRETRAIN_LEARNING_RATE': 0.0006,
    'PRETRAIN_LR_HALF_LIFE': 40,
}

# 0.0002 is what finetuning runs today and is the value under suspicion. The other two step
# down toward the range used for finetuning a pretrained transformer.
FINETUNE_LEARNING_RATES = [0.0002, 0.00005, 0.00001]

# None is the control: it holds the rate constant, so a difference between it and the other
# two is attributable to annealing rather than to the rate itself.
FINETUNE_HALF_LIVES = [None, 60, 20]

# Weights written by pretraining that a finetune reads back.
ENCODER_FILES = ('pretrained.pt', 'value_encoder.pt', 'event_encoder.pt')


def token(value):
    """Filename-safe token for a hyperparameter value."""
    if value is None:
        return 'flat'
    text = f'{value:g}'
    return text.replace('.', 'p').replace('-', 'm').replace('+', '')


def cells():
    """The grid, as (name, overrides) pairs."""
    for rate in FINETUNE_LEARNING_RATES:
        for half_life in FINETUNE_HALF_LIVES:
            name = f'ftdiag_lr{token(rate)}_hl{token(half_life)}'
            yield name, {'FINETUNE_LEARNING_RATE': rate, 'FINETUNE_LR_HALF_LIFE': half_life}


def write_config(base, name, overrides, output_dir, header):
    """Write one experiment config, and return its path."""
    config = dict(base)
    config['EXPERIMENT_NAME'] = name
    config.update(PRETRAIN_OVERRIDES)
    config.update(overrides)
    path = os.path.join(output_dir, f'{name}.yaml')
    with open(path, 'w') as f_out:
        f_out.write(header)
        yaml.safe_dump(config, f_out, default_flow_style=False, sort_keys=True)
    return path


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--base', default=BASE_CONFIG, help='Config the cells inherit from')
    parser.add_argument('--output_dir', default=OUTPUT_DIR, help='Where to write the configs')
    parser.add_argument('--fold', default='fold0', help='Fold the diagnostic runs on')
    args = parser.parse_args()

    with open(args.base) as f_in:
        base = yaml.safe_load(f_in)
    base.pop('HYPERPARAMETERS_TO_TUNE', None)
    os.makedirs(args.output_dir, exist_ok=True)

    header = (f'# Generated by generate_finetune_diagnostic.py from {args.base}\n'
              f'# Do not edit by hand -- regenerate instead.\n\n')

    pretrain_path = write_config(base, PRETRAIN_NAME, {}, args.output_dir, header)
    cell_paths = [(name, write_config(base, name, overrides, args.output_dir, header))
                  for name, overrides in cells()]

    model_dir = base['MODEL_DIR']
    print(f'Base config:  {args.base}')
    print(f'Encoder:      {PRETRAIN_NAME}  '
          f'({PRETRAIN_OVERRIDES["POSITION_ENCODING"]}, '
          f'lr {PRETRAIN_OVERRIDES["PRETRAIN_LEARNING_RATE"]}, '
          f'half-life {PRETRAIN_OVERRIDES["PRETRAIN_LR_HALF_LIFE"]})')
    print(f'Cells:        {len(cell_paths)}  '
          f'({len(FINETUNE_LEARNING_RATES)} rates x {len(FINETUNE_HALF_LIVES)} half-lives)\n')
    for name, path in cell_paths:
        print(f'  {name:<34} {path}')

    # slurm_run_experiment.sh indexes FOLDS by the array id and defaults to the five
    # manuscript folds, so a single-fold run has to name the fold and take one array task.
    launch = f'FOLDS="{args.fold}" sbatch --array=0-0 SLURM/slurm_run_experiment.sh'
    print('\n1. Pretrain once:')
    print(f'   TASKS=none {launch} {pretrain_path}')
    print('\n2. Link that encoder into every cell, so each one skips pretraining and they all')
    print('   finetune from identical weights:')
    print(f'   src="{model_dir}/{PRETRAIN_NAME}/{args.fold}/pretrained"')
    print(f'   for cell in {" ".join(name for name, _ in cell_paths)}; do')
    print(f'     dst="{model_dir}/$cell/{args.fold}/pretrained"; mkdir -p "$dst"')
    print(f'     for f in {" ".join(ENCODER_FILES)}; do ln -sf "$src/$f" "$dst/$f"; done')
    print('   done')
    print('\n3. Finetune every cell:')
    print(f'   for cfg in {args.output_dir}/ftdiag_lr*.yaml; do')
    print(f'     TASKS=mortality {launch} "$cfg"')
    print('   done')


if __name__ == '__main__':
    main()
